In [2]:
import pandas as pd
import itertools as it
import json
import os
sample_path = r"data/s2-sample/sample-S2-records"
corpus_path = r"data/s2-corpus/s2-corpus-000"
ids_csv = r"data/csv/ids.csv"
inCit_csv = r"data/csv/inCit.csv"

In [9]:
df = pd.read_json(sample_path, lines=True, encoding='utf8')

In [10]:
df.head()

,entities,journalVolume,journalPages,pmid,year,outCitations,s2Url,s2PdfUrl,id,authors,journalName,paperAbstract,inCitations,pdfUrls,title,doi,sources,doiUrl,venue
0,[],,,,1976.0,[],https://semanticscholar.org/paper/2cf5ee766dc5...,,2cf5ee766dc51c51cceab9df52f5fde2abed75bb,"[{'name': 'Margaret A. Burrel', 'ids': ['13436...",,,[],[],Ganelon's Act of Treason,,[],,
1,[],,,,2000.0,[],https://semanticscholar.org/paper/b3261cd65647...,,b3261cd65647a7d2b88e2de79eda9c92c390a4b0,"[{'name': 'Peng Bu-zhuo', 'ids': ['89414542']}]",,General Land Use of County in Present(GLUCP) r...,[],[],A Study on Making out and Appraising Programs ...,,[],,
2,[],,,,2019.0,[],https://semanticscholar.org/paper/6e44866b415e...,,6e44866b415e82138ef9bfa41911c2d874729628,"[{'name': 'Chung-Beom Ham', 'ids': ['120249433...",,,[],[],A Study on the Appearance of the Time Machine ...,10.21211/jhum.86.8,[],https://doi.org/10.21211/jhum.86.8,
3,[],,,,2005.0,[],https://semanticscholar.org/paper/376df9df0fee...,,376df9df0fee6361bbfa4eff2eee57fee54f9ea5,"[{'name': 'Yousef I. Salamin', 'ids': ['482623...",,Results from numerical calculations of the ene...,[],[],Electron acceleration in a tightly-focused vac...,10.1016/j.physleta.2004.12.049,[],https://doi.org/10.1016/j.physleta.2004.12.049,
4,[],,,,2001.0,[],https://semanticscholar.org/paper/b944072e258f...,,b944072e258f65c81c7a92b44599849aeacea68b,"[{'name': '嶋 明弘', 'ids': ['135768696']}, {'nam...",,,[],[],B-5-312 成層圏無線プラットフォーム搭載用dbfアンテナ送受信系キャリブレーション及び...,,[],,

In [27]:
corpus_iter = pd.read_json(corpus_path, lines=True, encoding='utf8', chunksize=10)

In [28]:
df2 = pd.DataFrame(it.islice(corpus_iter,100))

In [30]:
df2.head()

                                                   0
0    entities journalVolume                   jou...
1     entities journalVolume                  jou...
2     entities journalVolume                   jo...
3     entities journalVolume journalPages pmid  y...
4     entities journalVolume                  jou...

In [34]:
with open(corpus_path, 'r') as f:
    head = list(it.islice(f, 1))
    jd = json.load(head)
    #df2 = pd.read_json(it.islice(f, 10))
    print(jd)

AttributeError: 'list' object has no attribute 'read'

In [39]:
ids = []
inCitations = []

with open(corpus_path, 'r') as in_, open(:
    for x in range(10):
        js_line = json.loads(next(f))
        ids.append(js_line['id'])
        
        inCitations.append(js_line['inCitations']) 
print(inCitations)

[[], ['044119357f82caf0e300cab73cfe65af95b051d0', 'f87df96c5f5d21aedd3c37d56fe8a23e9cfe891d', '86ae30c9820b89c7414e758273d370769c6b6e3a', 'fce2841d623ae578177262389ecf2959914f0d15', '9127a557177563ac4f552ea4bb0060900f53b56f'], [], [], ['4cc357b5a4848fefd77001c9bbef987d20f43b4c', 'e1a877183126328072d0569323673eb3ab93f9f3', 'b799b807b6f718a36f4eb025f4166b1a5d5c68f0', '86176d4a10054d9526d9d815fa3ba114a08f6c6d', '18fd242275550ef360e7bc3891fcc30238aca9a0', 'b7a3c80e7a5f364dd4b73e4e057a2bd63a132bba', '7c34ee8d8121d6d18a64b8068d76df14313c07df', '1e1edd95a6b4c18e5531c8eaac1afbe89af11dc9', 'bc4f96d4feb7e90b0c70bc22d2e5414f47b5aad6', 'd722f33595fd62198ee49bae7398614921435a3d', '111568bcbcd74a3ca1a0df8f70116a6d9dd65aa8', '88ac1990157843539f2a98262ba86bdd26a271af', '83893e9598ee64af3fad920d0c36e83dc40ca2e0', 'cf44b0a531070334de5e998b4073ab9d9c1d9de4', 'c8d12826b1ad59fef0fc81036a764faab1502b81', '570bf49aa830161cb51fd946faa3930010333727', 'ae7f5e9b59fe6eef7549162ea1353c1daaaf6d4c', 'a4f6cba144154d671f5d9052d8e6a843aafa8a0f', '034b4c69d78fa56a2cf2ae1f88fa7959157078f9', '04960d52beb9e3c9aa6f8396627f0db580f45d2b', 'e5f840e93df112831286acf1580b11a69656227f', '9111a957ba83ebd114eb293c792367f22164d7d1', '7494e7263cff8b0489efcefaaca93a077278efd3', '6de0817c0bec5561d7b6bc75dd82740d38f6fc8d', '6fdc8d05837b965edb88347d7c46edd0a2bad066', '270f0d1acfe8ba970121a15f687f0d08e5728af4', '5db56a97386cb1ec0fa9c1fcc1d372e9345765f2', 'd1456bd6bfcd6d354cb15626bcbebf3fd3926048', '90adfa44b1de2dc3318063017d7395766a1c644a', '1b3d25a57c80ae17cc7c365c90776dd2e0dd6fb9', '4653cc2b4836cac2d77d1c8bfea02aa8cfa187c8', 'ac7321f60a112db910ed67a5fe45cb03793fd88f', 'ca70978c145f8f9f997e92cd07a353db75d236dc', '5e289d133f5c5c5e72d7d906a60534bebfd3b78f', 'aceb39d7d1aaf53c284b55483a65b796f4209a97', 'c7b6160cd1efd174f66ad90c09c71530d1bcb7e1', '5b9e7b45f5006b3657c0332d35d94493e3200ced', 'a889966b82b1fe348f81a6710c90ea53730823d5', '8f617f88b9ea70408e09860482b1a3b68cdcdc44', 'd02cea6d164a51be393e6d6621056c59c800259e', 'ce41f80657c1eae80b638416657761bffa4a69d2', 'c8b45a350d53682ab64032ae7a0e7724119b5ffd', '3dcf2d37a43de31f90eb6a595f96028db03488c8', 'b5a39f442deb99eca2ee5efea630bf28971b5bea', '91f9ff35cbcc8a7d9d9f1fd8050ee2ebb5ffd403', '84338dd533d548afb3ddf943b4a81ff5f13c31f8', '01ac133befe98144e5f8b967409982c6ac59521a', '36ccabc29801ca82ae4ef0ebbedaff59c36811d1', '9cb815a81ec263c7d3d456f7a8001f77ea2c38bc', '64a79a55bc4a301875a7b66975835393e400c897', '148ff4526fdc56b3dcefeed5b282188141c42ef8'], [], ['0a03da5ff1e53d4e59c52820070059a4d28b776e', 'e2074788c9bc061fea0b7527d4b72c80a51cdf7e', 'f301d2f055cc3d21bde2f3dedccb245e84cae60f', 'a549f452c8ba8a96c42b4f57b0acfc05b87733bf', '6e61e62b8a9f13f404d9e50f81c04c6f60b8d64b', 'a6d032fd2f42a22f25770be10ac7c54fce83c543', '58c7d9cc58ddb342f93ae5ea2697690814eeafc0', '0e39803dc8d8f2d72678c100cc393b3615e63f33', 'c8c96d7b01665e54b4d8550a604fd957f61becba', '3d04fc9b37ce92266980ef25fc7f8313668c29f6', '79a4f03c4a8aeb0fc7ecbfa829a30c6cf6e7c006', '2507ea006ce7b9b68275814570f7ca8734bd632c', 'ca2f64773628d2c3e75c1b3a76c2b21b91a705cc', '878f8bd2eb842581b0fb026b9211145145a4189f', '8ac414e360da85a78747c79c9777473e212cb58e', 'fb01dfe457d7e9c68b7767dc6c59d7cf33cd630d', 'f63a90429192a116c5514bdbc59c63fdb9b03fd0', '0b30a27646118828883e779387bee9986e34370b', 'fbc87f1b87fc17aa913f39f297a9ee744b1ca2c7', '6184d02e114bfb4bc5dcf8f27dd7e05f88a55ab5', '083e57402cbd682c171bd0b69226895ee6c084e2', 'a01e13caf7d8d16a1a9499274eeef9501872520b', 'f8bc3f74c0559e596011ceb6b8235a846da2db74', '00ec1aca4be9f907e66eea99553910e0065602c3', '0fd8dac3efa5537e49cf8b7a38eb274b56cd8f56', '466d7c79337783d1652a708e70e9cb75d20f77ef', 'b7903004cee29c267ce5fcbcfeb6d2c73c148dca', '279f45d6a32ffbdf99a973943bbd2c04f80b67da', '2a9abd9a405de4ac9e0877d54ae2c906a9b0b8b5', '0a486becf5410175161ecb45fa9e6ce92d8bcc35', '0ca182eb9f59588a9e6322ab112d4ecf602fda07'], [], [], []]

In [8]:
ids = []
inCitations = []
count = 0
with open(corpus_path, 'r') as in_, open(ids_csv, 'w') as out_1, open(inCit_csv,'w') as out_2:
    for line in in_:
        js_line = json.loads(line)
        count = count + 1
        idNum = js_line['id']
        #out_1.write(idNum+'\n')
        inCits = js_line['inCitations']
        for cit in inCits:
            out_2.write(idNum+','+cit+'\n')
        #print(js_line['id'])
print(count)

1000000